#!/usr/bin/env bash
set -euo pipefail

# === Config (edit as needed) ===
CONTAINER_NAME="${CONTAINER_NAME:-kali-container}" # your Kali container name
PF_CONF="${PF_CONF:-/etc/pf.conf}"
PF_ANCHOR_NAME="htb-container-nat"
PF_ANCHOR_FILE="/etc/pf.anchors/${PF_ANCHOR_NAME}"
PF_MARK_BEGIN="# HTB container NAT anchors (BEGIN)"
PF_MARK_END="# HTB container NAT anchors (END)"

# HTB common subnets (adjust if your .ovpn ships more specific routes)
HTB_ROUTES=(
  "10.10.0.0/16"
  "10.129.0.0/16"
)

usage() {
  cat <<EOF
Usage:
  sudo $0 --apply     # detect utun, write anchor, enable forwarding, add static routes inside the container
  sudo $0 --refresh   # after VPN reconnect/utun change, rewrite anchor and reload pf (container routes unchanged)
  sudo $0 --cleanup   # remove anchor/marked block and reload pf (won't touch your other pf rules)
  sudo $0 --status    # show pf/anchor/forwarding/container-route status

Env:
  CONTAINER_NAME   (default: kali-container)
  PF_CONF          (default: /etc/pf.conf)
EOF
}

require_cmd() { command -v "$1" >/dev/null 2>&1 || {
  echo "[!] missing command: $1"
  exit 1
}; }

container_exec() {
  if command -v container >/dev/null 2>&1; then
    container exec "$CONTAINER_NAME" "$@"
  elif command -v docker >/dev/null 2>&1; then
    docker exec "$CONTAINER_NAME" "$@"
  else
    echo "[!] neither 'container' nor 'docker' CLI found for exec" >&2
    exit 1
  fi
}

detect_utun() {
  # Prefer the utun that carries 10.10/10.129; else an active utun; else any utun.
  local u
  u=$(netstat -rn -f inet | awk '/(^10\.10\.|^10\.129\.)/ {print $NF}' | grep -E '^utun[0-9]+' | head -n1 || true)
  if [[ -n "${u:-}" ]]; then
    echo "$u"
    return 0
  fi
  for i in $(ifconfig -l); do
    [[ "$i" =~ ^utun[0-9]+$ ]] && if ifconfig "$i" 2>/dev/null | grep -q "status: active"; then
      echo "$i"
      return 0
    fi
  done
  for i in $(ifconfig -l); do [[ "$i" =~ ^utun[0-9]+$ ]] && {
    echo "$i"
    return 0
  }; done
  return 1
}

detect_container_net_and_gw() {
  local gw net
  gw=$(container_exec sh -lc "ip route | awk '/^default/ {print \$3; exit}'")
  net=$(container_exec sh -lc "ip route | awk '/dev[[:space:]]+eth0[[:space:]]+proto[[:space:]]+kernel/ {print \$1; exit}'")
  [[ -z "${gw:-}" || -z "${net:-}" ]] && {
    echo "[!] cannot detect container GW/subnet; is the container running? name: $CONTAINER_NAME" >&2
    exit 1
  }
  printf "%s|%s" "$gw" "$net"
}

enable_ip_forward() {
  echo "[*] enabling IPv4 forwarding on the host..."
  sysctl -w net.inet.ip.forwarding=1 >/dev/null
}

write_anchor_file() {
  local utun_if="${1:-}"
  local container_net="${2:-}"
  [[ -z "$utun_if" || -z "$container_net" ]] && {
    echo "[!] write_anchor_file: missing args"
    exit 2
  }
  echo "[*] writing anchor: ${PF_ANCHOR_FILE} (utun=${utun_if}, net=${container_net})"
  umask 022
  sudo tee "$PF_ANCHOR_FILE" >/dev/null <<EOF
# Auto-generated by kali_vpn_bridge.sh
# NAT: container subnet -> VPN interface
nat on ${utun_if} from ${container_net} to any -> (${utun_if})
# Optional allow: some systems have strict default filter policies
pass out on ${utun_if} from ${container_net} to any keep state
EOF
}

ensure_pf_anchors_block_in_pfconf() {
  # Ensure our anchor is loaded in the translation stage (must be before filtering).
  local blockfile
  blockfile=$(mktemp)
  cat >"$blockfile" <<EOF
${PF_MARK_BEGIN}
nat-anchor "${PF_ANCHOR_NAME}"
anchor "${PF_ANCHOR_NAME}"
load anchor "${PF_ANCHOR_NAME}" from "${PF_ANCHOR_FILE}"
${PF_MARK_END}
EOF

  if [[ ! -f "${PF_CONF}.bak_htb" ]]; then
    echo "[*] backing up ${PF_CONF} -> ${PF_CONF}.bak_htb"
    cp -p "$PF_CONF" "${PF_CONF}.bak_htb"
  fi

  # Remove any old marked block.
  if grep -q "${PF_MARK_BEGIN}" "$PF_CONF"; then
    awk -v begin="$PF_MARK_BEGIN" -v end="$PF_MARK_END" '
      $0 ~ begin {skip=1; next}
      $0 ~ end {skip=0; next}
      !skip {print}
    ' "$PF_CONF" >"${PF_CONF}.tmp1"
  else
    cp "$PF_CONF" "${PF_CONF}.tmp1"
  fi

  # Insert our block before the first 'anchor "com.apple/*"' (i.e., before filter stage).
  awk -v b="$blockfile" '
    BEGIN{ins=0}
    /^anchor "com\.apple\/\*"/ && !ins {
      while ((getline l < b) > 0) print l
      close(b); ins=1
    }
    {print}
    END{
      if(!ins){
        while ((getline l < b) > 0) print l
        close(b)
      }
    }
  ' "${PF_CONF}.tmp1" >"${PF_CONF}.tmp2"

  mv "${PF_CONF}.tmp2" "$PF_CONF"
  rm -f "${PF_CONF}.tmp1" "$blockfile"
}

reload_pf() {
  echo "[*] reloading pf..."
  pfctl -f "$PF_CONF" >/dev/null
  pfctl -e >/dev/null 2>&1 || true
}

add_routes_in_container() {
  local gw="${1:-}"
  [[ -z "$gw" ]] && {
    echo "[!] add_routes_in_container: missing gw"
    exit 2
  }
  echo "[*] adding static routes in container via GW=${gw} ..."
  for cidr in "${HTB_ROUTES[@]}"; do
    container_exec sh -lc "ip route replace ${cidr} via ${gw}" || true
  done
  echo "[*] container routes:"
  container_exec sh -lc "ip route | sed 's/^/    /'"
}

remove_pf_anchor_block() {
  echo "[*] removing pf marked block and anchor..."
  if [[ -f "$PF_CONF" ]] && grep -q "${PF_MARK_BEGIN}" "$PF_CONF"; then
    awk -v begin="$PF_MARK_BEGIN" -v end="$PF_MARK_END" '
      $0 ~ begin {skip=1; next}
      $0 ~ end {skip=0; next}
      !skip {print}
    ' "$PF_CONF" >"${PF_CONF}.tmp" && mv "${PF_CONF}.tmp" "$PF_CONF"
  fi
  [[ -f "$PF_ANCHOR_FILE" ]] && rm -f "$PF_ANCHOR_FILE"
  pfctl -f "$PF_CONF" >/dev/null || true
}

show_status() {
  echo "---- pf info ----"
  pfctl -s info | sed 's/^/    /'
  echo "---- anchors ----"
  pfctl -sn | sed 's/^/    /'
  echo "---- ${PF_ANCHOR_NAME} (NAT) ----"
  pfctl -a "${PF_ANCHOR_NAME}" -sn 2>/dev/null | sed 's/^/    /' || true
  echo "---- ${PF_ANCHOR_NAME} (FILTER) ----"
  pfctl -a "${PF_ANCHOR_NAME}" -sr 2>/dev/null | sed 's/^/    /' || true
  echo "---- forwarding ----"
  sysctl net.inet.ip.forwarding
  echo "---- container routes ----"
  container_exec sh -lc "ip route | sed 's/^/    /'" || true
}

do_apply() {
  require_cmd ifconfig
  require_cmd netstat
  require_cmd pfctl
  require_cmd awk
  require_cmd sysctl

  echo "[*] detecting VPN interface (utunX)..."
  local utun
  utun=$(detect_utun) || {
    echo "[!] no utun detected; connect your VPN GUI first"
    exit 1
  }
  echo "    selected: ${utun}"

  echo "[*] detecting container default gateway and subnet..."
  local pair gw net
  pair=$(detect_container_net_and_gw)
  gw="${pair%%|*}"
  net="${pair##*|}"
  echo "    GW:  ${gw}"
  echo "    NET: ${net}"

  enable_ip_forward
  write_anchor_file "${utun}" "${net}"
  ensure_pf_anchors_block_in_pfconf
  reload_pf
  add_routes_in_container "${gw}"
  show_status

  echo
  echo "[✔] Done. Validate:"
  echo "    - Host:     sudo tcpdump -ni ${utun}"
  echo "    - Container: ping -c1 10.10.10.10  or  nmap -Pn 10.10.10.10"
}

do_refresh() {
  require_cmd ifconfig
  require_cmd netstat
  require_cmd pfctl
  require_cmd sysctl
  echo "[*] re-detecting utun..."
  local utun
  utun=$(detect_utun) || {
    echo "[!] no utun detected"
    exit 1
  }
  echo "    utun: ${utun}"

  echo "[*] detecting container subnet..."
  local net pair
  pair=$(detect_container_net_and_gw)
  net="${pair##*|}"
  echo "    NET: ${net}"

  enable_ip_forward
  write_anchor_file "${utun}" "${net}"
  ensure_pf_anchors_block_in_pfconf
  reload_pf
  show_status
  echo "[✔] Refreshed NAT to ${utun}."
}

do_cleanup() {
  remove_pf_anchor_block
  echo "[*] (optional) disable IP forwarding: sudo sysctl -w net.inet.ip.forwarding=0"
  echo "[*] (optional) fully disable pf:       sudo pfctl -d"
  # Also remove the static routes inside the container (skip if absent)
  container_exec sh -lc 'for n in 10.10.0.0/16 10.129.0.0/16; do ip route del $n 2>/dev/null || true; done; ip route' || true
  show_status
  echo "[✔] Cleanup completed."
}

case "${1:-}" in
--apply) do_apply ;;
--refresh) do_refresh ;;
--cleanup) do_cleanup ;;
--status) show_status ;;
*)
  usage
  exit 1
  ;;
esac
