#!/usr/bin/env bash
set -euo pipefail

# === 配置（按需修改） ===
CONTAINER_NAME="${CONTAINER_NAME:-kali-container}" # 你的 Kali 容器名
PF_CONF="${PF_CONF:-/etc/pf.conf}"
PF_ANCHOR_NAME="htb-container-nat"
PF_ANCHOR_FILE="/etc/pf.anchors/${PF_ANCHOR_NAME}"
PF_MARK_BEGIN="# HTB container NAT anchors (BEGIN)"
PF_MARK_END="# HTB container NAT anchors (END)"

# HTB 常见网段（如 .ovpn 有更精确的 route 可改这里）
HTB_ROUTES=(
  "10.10.0.0/16"
  "10.129.0.0/16"
)

usage() {
  cat <<EOF
用法:
  sudo $0 --apply     # 侦测 utun + 写入 anchor + 开转发 + 在容器中加静态路由
  sudo $0 --refresh   # VPN 重连/utun 变更后，重写 anchor 并 reload pf（容器路由不动）
  sudo $0 --cleanup   # 移除 anchor/标记块并 reload（不动你的其他 pf 规则）
  sudo $0 --status    # 查看当前 pf/anchor/转发/容器路由状态

环境变量:
  CONTAINER_NAME   (默认: kali-container)
  PF_CONF          (默认: /etc/pf.conf)
EOF
}

require_cmd() { command -v "$1" >/dev/null 2>&1 || {
  echo "[!] 缺少命令: $1"
  exit 1
}; }

container_exec() {
  if command -v container >/dev/null 2>&1; then
    container exec "$CONTAINER_NAME" "$@"
  elif command -v docker >/dev/null 2>&1; then
    docker exec "$CONTAINER_NAME" "$@"
  else
    echo "[!] 未找到 'container' 或 'docker' CLI 可用于 exec" >&2
    exit 1
  fi
}

detect_utun() {
  # 优先找承载 10.10/10.129 的 utun；否则找 active utun；再不行任意 utun
  local u
  u=$(netstat -rn -f inet | awk '/(^10\.10\.|^10\.129\.)/ {print $NF}' | grep -E '^utun[0-9]+' | head -n1 || true)
  if [[ -n "${u:-}" ]]; then
    echo "$u"
    return 0
  fi
  for i in $(ifconfig -l); do
    [[ "$i" =~ ^utun[0-9]+$ ]] && if ifconfig "$i" 2>/dev/null | grep -q "status: active"; then
      echo "$i"
      return 0
    fi
  done
  for i in $(ifconfig -l); do [[ "$i" =~ ^utun[0-9]+$ ]] && {
    echo "$i"
    return 0
  }; done
  return 1
}

detect_container_net_and_gw() {
  local gw net
  gw=$(container_exec sh -lc "ip route | awk '/^default/ {print \$3; exit}'")
  net=$(container_exec sh -lc "ip route | awk '/dev[[:space:]]+eth0[[:space:]]+proto[[:space:]]+kernel/ {print \$1; exit}'")
  [[ -z "${gw:-}" || -z "${net:-}" ]] && {
    echo "[!] 无法探测容器网关/子网；容器是否在运行？名称: $CONTAINER_NAME" >&2
    exit 1
  }
  printf "%s|%s" "$gw" "$net"
}

enable_ip_forward() {
  echo "[*] 开启宿主机 IPv4 转发..."
  sysctl -w net.inet.ip.forwarding=1 >/dev/null
}

write_anchor_file() {
  local utun_if="${1:-}"
  local container_net="${2:-}"
  [[ -z "$utun_if" || -z "$container_net" ]] && {
    echo "[!] write_anchor_file 缺参"
    exit 2
  }
  echo "[*] 写入 anchor: ${PF_ANCHOR_FILE} (utun=${utun_if}, net=${container_net})"
  umask 022
  sudo tee "$PF_ANCHOR_FILE" >/dev/null <<EOF
# Auto-generated by kali_vpn_bridge.sh
# NAT: 容器子网 -> VPN 接口
nat on ${utun_if} from ${container_net} to any -> (${utun_if})
# 可选放行：部分系统默认 filter 比较严
pass out on ${utun_if} from ${container_net} to any keep state
EOF
}

ensure_pf_anchors_block_in_pfconf() {
  # 确保在 translation 阶段加载我们的 anchor（必须在 filter 段之前）
  local blockfile
  blockfile=$(mktemp)
  cat >"$blockfile" <<EOF
${PF_MARK_BEGIN}
nat-anchor "${PF_ANCHOR_NAME}"
anchor "${PF_ANCHOR_NAME}"
load anchor "${PF_ANCHOR_NAME}" from "${PF_ANCHOR_FILE}"
${PF_MARK_END}
EOF

  if [[ ! -f "${PF_CONF}.bak_htb" ]]; then
    echo "[*] 备份 ${PF_CONF} -> ${PF_CONF}.bak_htb"
    cp -p "$PF_CONF" "${PF_CONF}.bak_htb"
  fi

  # 移除旧标记块
  if grep -q "${PF_MARK_BEGIN}" "$PF_CONF"; then
    awk -v begin="$PF_MARK_BEGIN" -v end="$PF_MARK_END" '
      $0 ~ begin {skip=1; next}
      $0 ~ end {skip=0; next}
      !skip {print}
    ' "$PF_CONF" >"${PF_CONF}.tmp1"
  else
    cp "$PF_CONF" "${PF_CONF}.tmp1"
  fi

  # 将我们的块插到第一条 anchor "com.apple/*" 之前（即 filter 段之前）
  awk -v b="$blockfile" '
    BEGIN{ins=0}
    /^anchor "com\.apple\/\*"/ && !ins {
      while ((getline l < b) > 0) print l
      close(b); ins=1
    }
    {print}
    END{
      if(!ins){
        while ((getline l < b) > 0) print l
        close(b)
      }
    }
  ' "${PF_CONF}.tmp1" >"${PF_CONF}.tmp2"

  mv "${PF_CONF}.tmp2" "$PF_CONF"
  rm -f "${PF_CONF}.tmp1" "$blockfile"
}

reload_pf() {
  echo "[*] 重新加载 pf 配置..."
  pfctl -f "$PF_CONF" >/dev/null
  pfctl -e >/dev/null 2>&1 || true
}

add_routes_in_container() {
  local gw="${1:-}"
  [[ -z "$gw" ]] && {
    echo "[!] add_routes_in_container 缺参 gw"
    exit 2
  }
  echo "[*] 在容器内添加静态路由，经由 GW=${gw} ..."
  for cidr in "${HTB_ROUTES[@]}"; do
    container_exec sh -lc "ip route replace ${cidr} via ${gw}" || true
  done
  echo "[*] 容器当前路由："
  container_exec sh -lc "ip route | sed 's/^/    /'"
}

remove_pf_anchor_block() {
  echo "[*] 移除 pf 标记块与 anchor..."
  if [[ -f "$PF_CONF" ]] && grep -q "${PF_MARK_BEGIN}" "$PF_CONF"; then
    awk -v begin="$PF_MARK_BEGIN" -v end="$PF_MARK_END" '
      $0 ~ begin {skip=1; next}
      $0 ~ end {skip=0; next}
      !skip {print}
    ' "$PF_CONF" >"${PF_CONF}.tmp" && mv "${PF_CONF}.tmp" "$PF_CONF"
  fi
  [[ -f "$PF_ANCHOR_FILE" ]] && rm -f "$PF_ANCHOR_FILE"
  pfctl -f "$PF_CONF" >/dev/null || true
}

show_status() {
  echo "---- pf 状态 ----"
  pfctl -s info | sed 's/^/    /'
  echo "---- anchors 列表 ----"
  pfctl -sn | sed 's/^/    /'
  echo "---- ${PF_ANCHOR_NAME} (NAT) ----"
  pfctl -a "${PF_ANCHOR_NAME}" -sn 2>/dev/null | sed 's/^/    /' || true
  echo "---- ${PF_ANCHOR_NAME} (FILTER) ----"
  pfctl -a "${PF_ANCHOR_NAME}" -sr 2>/dev/null | sed 's/^/    /' || true
  echo "---- 转发开关 ----"
  sysctl net.inet.ip.forwarding
  echo "---- 容器路由 ----"
  container_exec sh -lc "ip route | sed 's/^/    /'" || true
}

do_apply() {
  require_cmd ifconfig
  require_cmd netstat
  require_cmd pfctl
  require_cmd awk
  require_cmd sysctl

  echo "[*] 侦测 VPN 接口 (utunX)..."
  local utun
  utun=$(detect_utun) || {
    echo "[!] 未检测到 utun；请先用 GUI 连接 VPN"
    exit 1
  }
  echo "    选用: ${utun}"

  echo "[*] 侦测容器默认网关与子网..."
  local pair gw net
  pair=$(detect_container_net_and_gw)
  gw="${pair%%|*}"
  net="${pair##*|}"
  echo "    GW: ${gw}"
  echo "    NET: ${net}"

  enable_ip_forward
  write_anchor_file "${utun}" "${net}"
  ensure_pf_anchors_block_in_pfconf
  reload_pf
  add_routes_in_container "${gw}"
  show_status

  echo
  echo "[✔] 完成。验证："
  echo "    - 宿主机: sudo tcpdump -ni ${utun}"
  echo "    - 容器内: ping -c1 10.10.10.10  或  nmap -Pn 10.10.10.10"
}

do_refresh() {
  require_cmd ifconfig
  require_cmd netstat
  require_cmd pfctl
  require_cmd sysctl
  echo "[*] 重新侦测 utun..."
  local utun
  utun=$(detect_utun) || {
    echo "[!] 未检测到 utun"
    exit 1
  }
  echo "    utun: ${utun}"

  echo "[*] 侦测容器子网..."
  local net pair
  pair=$(detect_container_net_and_gw)
  net="${pair##*|}"
  echo "    NET: ${net}"

  enable_ip_forward
  write_anchor_file "${utun}" "${net}"
  ensure_pf_anchors_block_in_pfconf
  reload_pf
  show_status
  echo "[✔] 已刷新 NAT 指向 ${utun}。"
}

do_cleanup() {
  remove_pf_anchor_block
  echo "[*] （可选）关闭 IP 转发： sudo sysctl -w net.inet.ip.forwarding=0"
  echo "[*] （可选）彻底停用 pf：  sudo pfctl -d"
  # 同步把容器静态路由去掉（不存在就跳过）
  container_exec sh -lc 'for n in 10.10.0.0/16 10.129.0.0/16; do ip route del $n 2>/dev/null || true; done; ip route' || true
  show_status
  echo "[✔] 清理完成。"
}

case "${1:-}" in
--apply) do_apply ;;
--refresh) do_refresh ;;
--cleanup) do_cleanup ;;
--status) show_status ;;
*)
  usage
  exit 1
  ;;
esac
